/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPlaylistsRouteImport } from './routes/_app.playlists'
import { Route as AppLiveRouteImport } from './routes/_app.live'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCatchupRouteImport } from './routes/_app.catchup'
import { Route as AppSeriesIndexRouteImport } from './routes/_app.series.index'
import { Route as AppMoviesIndexRouteImport } from './routes/_app.movies.index'
import { Route as AppSeriesIdRouteImport } from './routes/_app.series.$id'
import { Route as AppMovieIdRouteImport } from './routes/_app.movie.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsRoute = AppPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCatchupRoute = AppCatchupRouteImport.update({
  id: '/catchup',
  path: '/catchup',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIdRoute = AppSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMovieIdRoute = AppMovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catchup': typeof AppCatchupRoute
  '/home': typeof AppHomeRoute
  '/live': typeof AppLiveRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/movie/$id': typeof AppMovieIdRoute
  '/series/$id': typeof AppSeriesIdRoute
  '/movies/': typeof AppMoviesIndexRoute
  '/series/': typeof AppSeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catchup': typeof AppCatchupRoute
  '/home': typeof AppHomeRoute
  '/live': typeof AppLiveRoute
  '/playlists': typeof AppPlaylistsRoute
  '/settings': typeof AppSettingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/movie/$id': typeof AppMovieIdRoute
  '/series/$id': typeof AppSeriesIdRoute
  '/movies': typeof AppMoviesIndexRoute
  '/series': typeof AppSeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/catchup': typeof AppCatchupRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/playlists': typeof AppPlaylistsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/player/$id': typeof PlayerIdRoute
  '/_app/movie/$id': typeof AppMovieIdRoute
  '/_app/series/$id': typeof AppSeriesIdRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
  '/_app/series/': typeof AppSeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catchup'
    | '/home'
    | '/live'
    | '/playlists'
    | '/settings'
    | '/player/$id'
    | '/movie/$id'
    | '/series/$id'
    | '/movies/'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/catchup'
    | '/home'
    | '/live'
    | '/playlists'
    | '/settings'
    | '/player/$id'
    | '/movie/$id'
    | '/series/$id'
    | '/movies'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/catchup'
    | '/_app/home'
    | '/_app/live'
    | '/_app/playlists'
    | '/_app/settings'
    | '/player/$id'
    | '/_app/movie/$id'
    | '/_app/series/$id'
    | '/_app/movies/'
    | '/_app/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayerIdRoute: typeof PlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists': {
      id: '/_app/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AppPlaylistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catchup': {
      id: '/_app/catchup'
      path: '/catchup'
      fullPath: '/catchup'
      preLoaderRoute: typeof AppCatchupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/': {
      id: '/_app/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series/$id': {
      id: '/_app/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof AppSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movie/$id': {
      id: '/_app/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof AppMovieIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatchupRoute: typeof AppCatchupRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLiveRoute: typeof AppLiveRoute
  AppPlaylistsRoute: typeof AppPlaylistsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppMovieIdRoute: typeof AppMovieIdRoute
  AppSeriesIdRoute: typeof AppSeriesIdRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatchupRoute: AppCatchupRoute,
  AppHomeRoute: AppHomeRoute,
  AppLiveRoute: AppLiveRoute,
  AppPlaylistsRoute: AppPlaylistsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppMovieIdRoute: AppMovieIdRoute,
  AppSeriesIdRoute: AppSeriesIdRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
  AppSeriesIndexRoute: AppSeriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayerIdRoute: PlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
